[platformio]
src_dir = .
[env:aqi-main-pwm-example]
platform = espressif32@6.5.0
board = esp32-c3-devkitm-1
framework = arduino
build_src_filter = +<BatteryPwmReader.cpp> +<receiver_example.cpp>
build_flags = -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1
monitor_speed = 115200
